In [29]:
import pandas as pd

Este archivo, procesa la información de dos sucursales DEL y PAL, las limpia, y las combina en un nuevo archivo llamado ventas.csv

## Download data

(Opcional) Generar datos de ejemplo

Si no tienes ya un CSV de ventas, genera datos simulados:

```bash
python ../stores_data/data_generation.py
```

In [30]:
# Carga los archivos de dos sucursales en dos dataframes
df_del = pd.read_csv('../stores_data/raw/ventas_DEL.csv')
df_pal = pd.read_csv('../stores_data/raw/ventas_PAL.csv')

#### Explora la Sucursal 1

In [31]:
df_del.head()

,Invoice No,Date,Line,Product Code,Invoice Quantity,Unit Cost,Net Unit Price,Price List,Price Limit,Price Std,Category Name,Total
0,DEL1000,06/03/2026,10,ACA-169,6,7.80,9.61,10.57,9.13,9.61,Acabados,57.66
1,DEL1000,06/03/2026,20,TUB-352,6,13.23,17.80,19.58,16.91,17.80,Tuberías,106.80
2,DEL1001,19/11/2025,10,TUB-423,6,19.67,30.92,34.01,29.37,30.92,Tuberías,185.52
3,DEL1001,19/11/2025,20,FER-371,3,12.15,26.80,29.48,25.46,26.80,Ferretería,80.40
4,DEL1002,13/03/2026,10,TUB-109,2,15.50,22.34,24.57,21.22,22.34,Tuberías,44.68

In [32]:
df_del.info()

<class 'pandas.DataFrame'>
RangeIndex: 703 entries, 0 to 702
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice No        703 non-null    str
 1   Date              703 non-null    str
 2   Line              703 non-null    int64
 3   Product Code      703 non-null    str
 4   Invoice Quantity  703 non-null    int64
 5   Unit Cost         703 non-null    float64
 6   Net Unit Price    703 non-null    float64
 7   Price List        703 non-null    float64
 8   Price Limit       703 non-null    float64
 9   Price Std         703 non-null    float64
 10  Category Name     703 non-null    str
 11  Total             703 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 66.0 KB

In [33]:
print("Número de filas y columnas en df_del:", df_del.shape)

Número de filas y columnas en df_del: (703, 12)

#### Exlora la Sucursal 2

In [34]:
df_pal.head()

,Invoice No,Date,Line,Product Code,Invoice Quantity,Unit Cost,Net Unit Price,Price List,Price Limit,Price Std,Category Name,Total
0,PAL1000,24/02/2026,10,TUB-721,4,14.92,20.97,23.07,19.92,20.97,Tuberías,83.88
1,PAL1000,24/02/2026,20,SEG-715,4,35.36,46.95,51.65,44.60,46.95,Seguridad,187.80
2,PAL1000,24/02/2026,30,PLY-271,3,25.39,44.95,49.45,42.70,44.95,Plywood,134.85
3,PAL1001,24/06/2026,10,CEM-487,2,20.87,33.09,36.40,31.44,33.09,Cemento,66.18
4,PAL1001,24/06/2026,20,CEM-946,4,8.80,12.23,13.45,11.62,12.23,Cemento,48.92

In [35]:
df_pal.info()

<class 'pandas.DataFrame'>
RangeIndex: 617 entries, 0 to 616
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice No        617 non-null    str
 1   Date              617 non-null    str
 2   Line              617 non-null    int64
 3   Product Code      617 non-null    str
 4   Invoice Quantity  617 non-null    int64
 5   Unit Cost         617 non-null    float64
 6   Net Unit Price    617 non-null    float64
 7   Price List        617 non-null    float64
 8   Price Limit       617 non-null    float64
 9   Price Std         617 non-null    float64
 10  Category Name     617 non-null    str
 11  Total             617 non-null    float64
dtypes: float64(6), int64(2), str(4)
memory usage: 58.0 KB

In [36]:
print("Número de filas y columnas en df_pal:", df_pal.shape)

Número de filas y columnas en df_pal: (617, 12)

## Process and merge data

In [37]:
# Unir los dos DataFrames en uno
df_total = pd.concat([df_del, df_pal], ignore_index=True)
df_total.info()

<class 'pandas.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Invoice No        1320 non-null   str
 1   Date              1320 non-null   str
 2   Line              1320 non-null   int64
 3   Product Code      1320 non-null   str
 4   Invoice Quantity  1320 non-null   int64
 5   Unit Cost         1320 non-null   float64
 6   Net Unit Price    1320 non-null   float64
 7   Price List        1320 non-null   float64
 8   Price Limit       1320 non-null   float64
 9   Price Std         1320 non-null   float64
 10  Category Name     1320 non-null   str
 11  Total             1320 non-null   float64
dtypes: float64(6), int64(2), str(4)
memory usage: 123.9 KB

In [38]:
# Crea una nueva columna Sede
df_total['Sede'] = df_total['Invoice No'].str[:3]
print(df_total.head())

  Invoice No        Date  Line Product Code  Invoice Quantity  Unit Cost  \
0    DEL1000  06/03/2026    10      ACA-169                 6       7.80
1    DEL1000  06/03/2026    20      TUB-352                 6      13.23
2    DEL1001  19/11/2025    10      TUB-423                 6      19.67
3    DEL1001  19/11/2025    20      FER-371                 3      12.15
4    DEL1002  13/03/2026    10      TUB-109                 2      15.50

   Net Unit Price  Price List  Price Limit  Price Std Category Name   Total  \
0            9.61       10.57         9.13       9.61      Acabados   57.66
1           17.80       19.58        16.91      17.80      Tuberías  106.80
2           30.92       34.01        29.37      30.92      Tuberías  185.52
3           26.80       29.48        25.46      26.80    Ferretería   80.40
4           22.34       24.57        21.22      22.34      Tuberías   44.68

  Sede
0  DEL
1  DEL
2  DEL
3  DEL
4  DEL

In [39]:
#mover la columna sede al comienzo del dataframe
# Primero, extraemos la columna 'Sede' de su posición actual
columna_sede = df_total.pop('Sede')

# Luego, la insertamos en la posición 0 (la primera columna)
df_total.insert(0, 'Sede', columna_sede)

df_total.info()

<class 'pandas.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Sede              1320 non-null   str
 1   Invoice No        1320 non-null   str
 2   Date              1320 non-null   str
 3   Line              1320 non-null   int64
 4   Product Code      1320 non-null   str
 5   Invoice Quantity  1320 non-null   int64
 6   Unit Cost         1320 non-null   float64
 7   Net Unit Price    1320 non-null   float64
 8   Price List        1320 non-null   float64
 9   Price Limit       1320 non-null   float64
 10  Price Std         1320 non-null   float64
 11  Category Name     1320 non-null   str
 12  Total             1320 non-null   float64
dtypes: float64(6), int64(2), str(5)
memory usage: 134.2 KB

## Create a CSV (ventas.csv) file with 2 stores

In [40]:
# Exportar a CSV
df_total.to_csv('../stores_data/processed/ventas.csv', index=False)